import React, { useState } from 'react';
import { StyleSheet, View, FlatList, Alert, TouchableWithoutFeedback, Keyboard } from 'react-native';
import Header from '../components/ToDoHeader';
import TodoItem from '../components/TodoItem';
import ToDoAdd from '../components/ToDoAdd';
import Sandbox from '../components/Sandbox';


export default function TodoScreen() {
    const [todo, setTodo] = useState([
        { text: 'find work', key: '1' },
        { text: 'do laundry', key: '2'},
        { text: 'play Civ V', key: '3'}
    ]);

    const pressHandler = (key) => {
      setTodo((prevTodos) => {
        return prevTodos.filter(todos => todos.key != key);
      });
    };

    const submitHandler = (text) => {
    if(text.length > 3){
      setText('');
      setTodo(prevTodos => {
        return [
          // key can be generated by a 3rd party key instead if need be
          { text, key: Math.random().toString() },
          ...prevTodos
        ];
      });
    } else {
      Alert.alert('Sorry, I cant do that Dave', 'Todo must be over 3 characters long', [
        {text: 'Understood', onPress: () => console.log('alert closed') }
      ]);
    }
  };

    return (
      <Sandbox />
      // <TouchableWithoutFeedback onPress={() => Keyboard.dismiss()}>
      //   <View style={styles.container}>
      //       <Header />
      //       <View style={styles.content}>
      //           <ToDoAdd submitHandler={submitHandler} />
      //           <View style={styles.list}>
      //               <FlatList
      //                   data={todo}
      //                   renderItem={({ item }) => (
      //                       <TodoItem item={item} pressHandler={pressHandler}/>
      //                   )}
      //               />
      //           </View>
      //       </View>
      //   </View>
      // </TouchableWithoutFeedback>
    );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  content: {
    padding: 40,
  },
  list: {
    marginTop: 20,
  },
});